version: '3.6'
services:
  telegraf:
    image: library/telegraf:latest
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - speedtest_data:/usr/speedtest
    depends_on:
      - influxdb
    links:
      - influxdb
  
  speedtest:
    build: speedtest/.
    volumes: 
      - speedtest_data:/usr/speedtest
    depends_on: 
      - influxdb

  influxdb:
    image: influxdb:latest
    env_file: configuration.env
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana_data: {}
  influxdb_data: {}
  speedtest_data: {}
