{
 "title": "Net Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Network Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Ping Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "nos.pt" }
     ]
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "tail",
     "select": [
      [
       { "params": [ "Download" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "tail",
     "select": [
      [
       { "params": [ "Upload" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Ping Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Google",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "ping",
     "query": "SELECT \"average_response_ms\" FROM \"ping\" WHERE (\"url\" = 'google.com') AND $timeFilter",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "google.com" }
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "google.com" }
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "minimum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "google.com" }
     ]
    }
   ]
  },
  {
   "title": "Youtube",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "ping",
     "query": "SELECT \"average_response_ms\" FROM \"ping\" WHERE (\"url\" = 'google.com') AND $timeFilter",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "youtube.com" }
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "youtube.com" }
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "minimum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "youtube.com" }
     ]
    }
   ]
  },
  {
   "title": "Facebook",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "ping",
     "query": "SELECT \"average_response_ms\" FROM \"ping\" WHERE (\"url\" = 'google.com') AND $timeFilter",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "facebook.com" }
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "facebook.com" }
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "minimum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "facebook.com" }
     ]
    }
   ]
  },
  {
   "title": "Observador",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "ping",
     "query": "SELECT \"average_response_ms\" FROM \"ping\" WHERE (\"url\" = 'google.com') AND $timeFilter",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "observador.pt" }
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "observador.pt" }
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "minimum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "observador.pt" }
     ]
    }
   ]
  },
  {
   "title": "RTP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "ping",
     "query": "SELECT \"average_response_ms\" FROM \"ping\" WHERE (\"url\" = 'google.com') AND $timeFilter",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "rtp.pt" }
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "rtp.pt" }
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "minimum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "rtp.pt" }
     ]
    }
   ]
  },
  {
   "title": "CERN",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Average",
     "measurement": "ping",
     "query": "SELECT \"average_response_ms\" FROM \"ping\" WHERE (\"url\" = 'google.com') AND $timeFilter",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "home.cern" }
     ]
    },
    {
     "alias": "Maximum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "home.cern" }
     ]
    },
    {
     "alias": "Minimum",
     "measurement": "ping",
     "select": [
      [
       { "params": [ "minimum_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "home.cern" }
     ]
    }
   ]
  }
 ]
}